### ISSUE TITLE
Trollius Rasing AssertionError

### ISSUE THREAD

**Issue by halojemrufus** [quantmind/pulsar#136]
When running some of the examples, AssertionError is being raised. For example:

# python examples/tweets/manage.py
```
22:11:27 [p=2197, t=140624344975104, INFO, pulsar.arbiter] mailbox serving on 127.0.0.1:58411
22:11:27 [p=2197, t=140624344975104, INFO, pulsar.arbiter] started
22:11:27 [p=2197, t=140624344975104, INFO, pulsar.pulsards] started
22:11:27 [p=2197, t=140624344975104, INFO, pulsar.pulsards] pulsards serving on 127.0.0.1:6410
22:11:27 [p=2197, t=140624344975104, ERROR, pulsar.twitter_server] Please specify the "twitter_api_key" parameter in your config.py file
22:11:27 [p=2197, t=140624344975104, INFO, pulsar.server] started
22:11:27 [p=2204, t=140624344975104, INFO, pulsar.server.worker] server serving on 127.0.0.1:8060
22:11:27 [p=2204, t=140624344975104, INFO, pulsar.server.worker] started
22:11:28 [p=2197, t=140624344975104, ERROR, trollius] Exception in callback <pulsar.async.eventloop.LoopingCall object at 0x7fe59d3ea0f0>()
handle: <TimerHandle when=5983.248157817 <pulsar.async.eventloop.LoopingCall object at 0x7fe59d3ea0f0>()>
Traceback (most recent call last):
  File "/opt/pixspan/app/pixdev_3/lib/python3.4/site-packages/pulsar/apps/data/stores/pulsards/startds.py", line 41, in start_store
    yield client.ping()
  File "/opt/pixspan/app/pixdev_3/lib/python3.4/site-packages/pulsar/async/futures.py", line 65, in yield_from
    value = yield From(result)
  File "/opt/pixspan/app/pixdev_3/lib/python3.4/site-packages/pulsar/async/futures.py", line 388, in _wakeup
    value = future.result()
  File "/opt/pixspan/app/pixdev_3/lib/python3.4/site-packages/trollius/futures.py", line 287, in result
    raise self._exception
  File "/opt/pixspan/app/pixdev_3/lib/python3.4/site-packages/trollius/tasks.py", line 251, in _step
    result = coro.throw(exc)
  File "/opt/pixspan/app/pixdev_3/lib/python3.4/site-packages/pulsar/async/futures.py", line 51, in yield_from
    result = coro.throw(exc)
  File "/opt/pixspan/app/pixdev_3/lib/python3.4/site-packages/pulsar/apps/data/stores/redis/store.py", line 78, in execute
    connection = yield self._pool.connect()
  File "/opt/pixspan/app/pixdev_3/lib/python3.4/site-packages/pulsar/async/futures.py", line 65, in yield_from
    value = yield From(result)
  File "/opt/pixspan/app/pixdev_3/lib/python3.4/site-packages/pulsar/async/futures.py", line 388, in _wakeup
    value = future.result()
  File "/opt/pixspan/app/pixdev_3/lib/python3.4/site-packages/trollius/futures.py", line 287, in result
    raise self._exception
  File "/opt/pixspan/app/pixdev_3/lib/python3.4/site-packages/trollius/tasks.py", line 251, in _step
    result = coro.throw(exc)
  File "/opt/pixspan/app/pixdev_3/lib/python3.4/site-packages/pulsar/async/futures.py", line 51, in yield_from
    result = coro.throw(exc)
  File "/opt/pixspan/app/pixdev_3/lib/python3.4/site-packages/pulsar/async/clients.py", line 70, in connect
    connection = yield self._get()
  File "/opt/pixspan/app/pixdev_3/lib/python3.4/site-packages/pulsar/async/futures.py", line 65, in yield_from
    value = yield From(result)
  File "/opt/pixspan/app/pixdev_3/lib/python3.4/site-packages/pulsar/async/futures.py", line 388, in _wakeup
    value = future.result()
  File "/opt/pixspan/app/pixdev_3/lib/python3.4/site-packages/trollius/futures.py", line 287, in result
    raise self._exception
  File "/opt/pixspan/app/pixdev_3/lib/python3.4/site-packages/trollius/tasks.py", line 251, in _step
    result = coro.throw(exc)
  File "/opt/pixspan/app/pixdev_3/lib/python3.4/site-packages/pulsar/async/futures.py", line 51, in yield_from
    result = coro.throw(exc)
  File "/opt/pixspan/app/pixdev_3/lib/python3.4/site-packages/pulsar/async/clients.py", line 98, in _get
    connection = yield self._creator()
  File "/opt/pixspan/app/pixdev_3/lib/python3.4/site-packages/pulsar/async/futures.py", line 65, in yield_from
    value = yield From(result)
  File "/opt/pixspan/app/pixdev_3/lib/python3.4/site-packages/pulsar/async/futures.py", line 388, in _wakeup
    value = future.result()
  File "/opt/pixspan/app/pixdev_3/lib/python3.4/site-packages/trollius/futures.py", line 287, in result
    raise self._exception
  File "/opt/pixspan/app/pixdev_3/lib/python3.4/site-packages/trollius/tasks.py", line 251, in _step
    result = coro.throw(exc)
  File "/opt/pixspan/app/pixdev_3/lib/python3.4/site-packages/pulsar/apps/data/stores/redis/store.py", line 99, in connect
    protocol_factory, host, port))
  File "/opt/pixspan/app/pixdev_3/lib/python3.4/site-packages/pulsar/async/futures.py", line 388, in _wakeup
    value = future.result()
  File "/opt/pixspan/app/pixdev_3/lib/python3.4/site-packages/trollius/futures.py", line 287, in result
    raise self._exception
  File "/opt/pixspan/app/pixdev_3/lib/python3.4/site-packages/trollius/tasks.py", line 251, in _step
    result = coro.throw(exc)
  File "/opt/pixspan/app/pixdev_3/lib/python3.4/site-packages/trollius/base_events.py", line 600, in create_connection
    raise exceptions[0]
  File "/opt/pixspan/app/pixdev_3/lib/python3.4/site-packages/trollius/base_events.py", line 587, in create_connection
    yield From(self.sock_connect(sock, address))
  File "/opt/pixspan/app/pixdev_3/lib/python3.4/site-packages/pulsar/async/futures.py", line 388, in _wakeup
    value = future.result()
  File "/opt/pixspan/app/pixdev_3/lib/python3.4/site-packages/trollius/futures.py", line 287, in result
    raise self._exception
  File "/opt/pixspan/app/pixdev_3/lib/python3.4/site-packages/trollius/selector_events.py", line 403, in _sock_connect_cb
    wrap_error(_get_socket_error, sock, address)
  File "/opt/pixspan/app/pixdev_3/lib/python3.4/site-packages/trollius/py33_exceptions.py", line 144, in wrap_error
    return func(*args, **kw)
  File "/opt/pixspan/app/pixdev_3/lib/python3.4/site-packages/trollius/selector_events.py", line 46, in _get_socket_error
    raise OSError(err, 'Connect call failed %s' % (address,))
ConnectionRefusedError: [Errno 111] Connect call failed ('127.0.0.1', 6410)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/pixspan/app/pixdev_3/lib/python3.4/site-packages/trollius/events.py", line 151, in _run
    self._callback(*self._args)
  File "/opt/pixspan/app/pixdev_3/lib/python3.4/site-packages/pulsar/async/eventloop.py", line 88, in __call__
    self._continue()
  File "/opt/pixspan/app/pixdev_3/lib/python3.4/site-packages/pulsar/async/eventloop.py", line 97, in _continue
    loop._add_callback(handler)
  File "/opt/pixspan/app/pixdev_3/lib/python3.4/site-packages/trollius/base_events.py", line 1017, in _add_callback
    assert not isinstance(handle, events.TimerHandle)
AssertionError
```

**Comment by lsbardel** [comment]
Thanks, I'll have a look
