### ISSUE TITLE
Error when specifying the config file on the commandline

### ISSUE THREAD

**Issue by pvanderlinden** [quantmind/pulsar#170]
When running lux with a different config file through the --config commandline parameter lux fails to import it.

For example when having a module on the path called `testconfig` and I run manage with `--config testconfig`, I get the following traceback:
```
Traceback (most recent call last):
  File "/home/paul/.virtualenvs/someproject/bin/someproject", line 9, in <module>
    load_entry_point('someproject==0.1.0', 'console_scripts', 'someproject')()
  File "/home/paul/repos/someproject/someproject/__init__.py", line 18, in main
    lux.execute_from_config('someproject.config', **kwargs)
  File "/home/paul/.virtualenvs/someproject/src/lux/lux/core/app.py", line 51, in execute_from_config
    return execute_app(App(config_file, **params))
  File "/home/paul/.virtualenvs/someproject/src/lux/lux/core/app.py", line 70, in execute_app
    application = app.commands()
  File "/home/paul/.virtualenvs/someproject/src/lux/lux/core/app.py", line 111, in commands
    return Application(self, handler=False)
  File "/home/paul/.virtualenvs/someproject/src/lux/lux/core/app.py", line 258, in __init__
    self.config = self._build_config(callable._config_file)
  File "/home/paul/.virtualenvs/someproject/src/lux/lux/core/app.py", line 697, in _build_config
    return self._build_config(config_module.__file__)
  File "/home/paul/.virtualenvs/someproject/src/lux/lux/core/app.py", line 684, in _build_config
    module = import_module(module_name)
  File "/home/paul/.virtualenvs/someproject/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2212, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2212, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2224, in _find_and_load_unlocked
ImportError: No module named '/home/paul/'
```

**Comment by pvanderlinden** [comment]
This is a bug in lux, not in pulsar: https://github.com/quantmind/lux/issues/229
