### ISSUE TITLE
yield from loop.run_in_executor(...) results in headers not set exception

### ISSUE THREAD

**Issue by thedrow** [quantmind/pulsar#174]
I have the following Router object:
```python
from asyncio import events
from concurrent.futures import ThreadPoolExecutor

from pulsar.apps.wsgi import Router, route

pool = ThreadPoolExecutor()

class GithubWebhooks(Router):
    def post(self, request):
        request.response.status_code = 200

        return request.response

    @route(rule='/push', method='POST')
    def push(self, request):
        loop = events.get_event_loop()
        body_data = yield from loop.run_in_executor(pool, request.body_data)

        return request.response
```

When I post something to /push I get the following exception:
```
00:53:56 [p=4424, t=140280307545856, CRITICAL, pulsar.wsgi] Unhandled exception during HTTP response @ POST "/push".

pulsar.cache={'app_handler': /push, 'mixins': {}, 'cfg': <pulsar.utils.config.Config object at 0x7f95878d6518>, 'content_types': ContentAccept([('application/json', 1)]), 'response': WsgiResponse(500 Internal Server Error), 'content_type_options': ('application/json', {}), 'data_and_files': ({'x': 'y'}, None), 'handle_wsgi_error': True, 'urlargs': {}}
SERVER_NAME=localhost
SERVER_SOFTWARE=pulsar/1.0.3
HTTP_CONNECTION=keep-alive
CONTENT_TYPE=application/json
wsgi.multiprocess=True
HTTP_USER_AGENT=HTTPie/0.9.2
wsgi.input=<_io.BytesIO object at 0x7f958706e728>
RAW_URI=/push
REMOTE_ADDR=127.0.0.1
SERVER_PROTOCOL=HTTP/1.1
HTTP_HOST=localhost:8060
HTTP_ACCEPT=application/json
REMOTE_PORT=39534
REQUEST_METHOD=POST
QUERY_STRING=
PATH_INFO=/push
wsgi.errors=<_io.TextIOWrapper name='<stderr>' mode='w' encoding='UTF-8'>
pulsar.connection=server 127.0.0.1:39534 session 1
wsgi.multithread=False
SCRIPT_NAME=
wsgi.run_once=False
SERVER_PORT=8060
CONTENT_LENGTH=10
HTTP_ACCEPT_ENCODING=gzip, deflate
wsgi.url_scheme=http
wsgi.version=(1, 0)
pulsar.cfg=<pulsar.utils.config.Config object at 0x7f95878d6518>
Traceback (most recent call last):
  File "/home/omer/.virtualenvs/drifter/lib/python3.5/site-packages/pulsar/apps/wsgi/server.py", line 488, in _response
    result = self.write(chunk)
  File "/home/omer/.virtualenvs/drifter/lib/python3.5/site-packages/pulsar/apps/wsgi/server.py", line 437, in write
    tosend = self.get_headers()
  File "/home/omer/.virtualenvs/drifter/lib/python3.5/site-packages/pulsar/apps/wsgi/server.py", line 548, in get_headers
    raise HttpException('Headers not set.')
pulsar.utils.exceptions.HttpException: Headers not set.
```
I might be doing something completely wrong here but there are no examples to how to attach a concurrent.futures Future to the pulsar event loop.
There's no good reason to do this since ujson (which I am using) never releases the GIL but I'm trying to learn what is possible and what isn't with Pulsar.
In any case, the exception is unclear and I'd consider it a bug.

**Comment by lsbardel** [comment]
Your ``push`` method returns a coroutine (generator) and therefore it does not comply with pulsar [asynchronous wsgi specification](https://pythonhosted.org/pulsar/apps/wsgi/async.html#application-handlers).
The server thinks you are returning an iterator an therefore it treats at such, in the same way as standard wsgi does.

In python 3.5 we can distinguish between coroutines and generators thanks to the new ``async`` keyword. The new syntax will allow for coroutines to be returned (and therefore your example will work), but for now that is not supported.

For now, if you want an async application handler you need to return a future, not a coroutine. In your case you could do:
```python
   @route(rule='/push', method='POST')
    def push(self, request):
        return asyncio.async(self._push(request))

    def _push(self, request):
        body_data = yield from request.body_data
        return request.response
```
The error message is correct. You returned a generator and did not set the headers. Returning the ``request.response`` object as result of the future will be set the headers for you.

**Comment by thedrow** [comment]
I don't see it documented anywhere. Also async is deprecated. It's called ensure_future in 3.5.
