### ISSUE TITLE
 AttributeError: 'SSLContext' object has no attribute 'wrap_bio' when performing an async HTTPS request 

### ISSUE THREAD

**Issue by thedrow** [quantmind/pulsar#175]
The following code:
```python
class GithubWebhooks(Router):

    def post(self, request):
        return asyncio.ensure_future(self._process_request(request))

    def _process_request(self, request):
        client = http.HttpClient()
        body_data = request.body_data()
        response = request.response
        request_ip = ipaddress.ip_address('{0}'.format(request.get_client_address()))
        if os.environ.get('GHE_ADDRESS', None):
            hook_blocks = [os.environ.get('GHE_ADDRESS')]
        # Otherwise get the hook address blocks from the API.
        else:
            metadata = yield from client.get('https://api.github.com/meta')
            hook_blocks = ujson.loads(metadata.data)

        # Check if the POST request is from github.com or GHE
        for block in hook_blocks:
            if ipaddress.ip_address(request_ip) in ipaddress.ip_network(block):
                break  # the remote_addr is within the network range of github.
        else:
            response.status_code = HTTPStatus.FORBIDDEN
        if request.environ.get('X-GitHub-Event') == "ping":
            return response
        if request.environ.get('X-GitHub-Event') != "push":
            return response
        response.status_code = HTTPStatus.CREATED
        return response
```
produces this exception:
```
23:57:57 [p=30597, t=140025971271424, CRITICAL, pulsar.wsgi] Unhandled exception during HTTP response @ POST "/".

pulsar.cache={'urlargs': {}, 'app_handler': /, 'content_types': ContentAccept([('application/json', 1)]), 'handle_wsgi_error': True, 'content_type_options': ('application/json', {}), 'data_and_files': ({'x': 'y'}, None), 'response': WsgiResponse(500 Internal Server Error), 'mixins': {}, 'cfg': <pulsar.utils.config.Config object at 0x7f5a4f9e85c0>}
RAW_URI=/
wsgi.run_once=False
REQUEST_METHOD=POST
REMOTE_ADDR=127.0.0.1
QUERY_STRING=
REMOTE_PORT=33206
CONTENT_TYPE=application/json
CONTENT_LENGTH=10
pulsar.connection=server 127.0.0.1:33206 session 2
wsgi.multiprocess=True
HTTP_ACCEPT=application/json
wsgi.url_scheme=http
wsgi.multithread=False
SERVER_PORT=8060
SERVER_SOFTWARE=pulsar/1.0.3
wsgi.version=(1, 0)
PATH_INFO=/
HTTP_ACCEPT_ENCODING=gzip, deflate
pulsar.cfg=<pulsar.utils.config.Config object at 0x7f5a4f9e85c0>
wsgi.errors=<_io.TextIOWrapper name='<stderr>' mode='w' encoding='UTF-8'>
SERVER_PROTOCOL=HTTP/1.1
HTTP_HOST=localhost:8060
HTTP_CONNECTION=keep-alive
wsgi.input=<_io.BytesIO object at 0x7f5a4e0e1e08>
SCRIPT_NAME=
SERVER_NAME=localhost
HTTP_USER_AGENT=HTTPie/0.9.2
Traceback (most recent call last):
  File "/home/omer/.virtualenvs/drifter/lib/python3.5/site-packages/pulsar/apps/wsgi/handlers.py", line 169, in _async
    response = yield from response
  File "/home/omer/.pyenv/versions/3.5.0/lib/python3.5/asyncio/futures.py", line 385, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/home/omer/.pyenv/versions/3.5.0/lib/python3.5/asyncio/tasks.py", line 288, in _wakeup
    value = future.result()
  File "/home/omer/.pyenv/versions/3.5.0/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/home/omer/.pyenv/versions/3.5.0/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(value)
  File "/home/omer/Documents/Projects/drifter/drifter-configuration-collector/src/collector/github.py", line 28, in _process_request
    metadata = yield from client.get('https://api.github.com/meta', timeout=1000)
  File "/home/omer/.pyenv/versions/3.5.0/lib/python3.5/asyncio/tasks.py", line 378, in wait_for
    return fut.result()
  File "/home/omer/.pyenv/versions/3.5.0/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/home/omer/.pyenv/versions/3.5.0/lib/python3.5/asyncio/tasks.py", line 237, in _step
    result = coro.throw(exc)
  File "/home/omer/.virtualenvs/drifter/lib/python3.5/site-packages/pulsar/apps/http/__init__.py", line 1128, in _request
    conn = yield from pool.connect()
  File "/home/omer/.virtualenvs/drifter/lib/python3.5/site-packages/pulsar/async/clients.py", line 89, in connect
    connection = yield from self._get()
  File "/home/omer/.virtualenvs/drifter/lib/python3.5/site-packages/pulsar/async/clients.py", line 120, in _get
    connection = yield from self._creator()
  File "/home/omer/.virtualenvs/drifter/lib/python3.5/site-packages/pulsar/apps/http/__init__.py", line 1211, in _connect
    self.create_protocol, host, port, ssl=ssl)
  File "/home/omer/.pyenv/versions/3.5.0/lib/python3.5/asyncio/base_events.py", line 669, in create_connection
    sock, protocol_factory, ssl, server_hostname)
  File "/home/omer/.pyenv/versions/3.5.0/lib/python3.5/asyncio/base_events.py", line 692, in _create_connection_transport
    yield from waiter
  File "/home/omer/.pyenv/versions/3.5.0/lib/python3.5/asyncio/futures.py", line 385, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/home/omer/.pyenv/versions/3.5.0/lib/python3.5/asyncio/tasks.py", line 288, in _wakeup
    value = future.result()
  File "/home/omer/.pyenv/versions/3.5.0/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/home/omer/.pyenv/versions/3.5.0/lib/python3.5/asyncio/sslproto.py", line 561, in _on_handshake_complete
    raise handshake_exc
  File "/home/omer/.pyenv/versions/3.5.0/lib/python3.5/asyncio/sslproto.py", line 617, in _process_write_backlog
    self._on_handshake_complete)
  File "/home/omer/.pyenv/versions/3.5.0/lib/python3.5/asyncio/sslproto.py", line 128, in do_handshake
    self._sslobj = self._context.wrap_bio(
AttributeError: 'SSLContext' object has no attribute 'wrap_bio'
```
I'm following the documentation as closely as possible. Any ideas what could be wrong?

**Comment by thedrow** [comment]
It seems that SSL support is broken on 3.5. See #176

**Comment by lsbardel** [comment]
Can you provide the pulsar version you are using?
This issue should be fixed in pulsar 1.0.5.

**Comment by thedrow** [comment]
I was using the latest from pip.
When I installed the version from the py35 branch the exception did not occur. 
Will these fixes be backported to 1.0.x as well or do I have to wait for a version that supports python 3.5?

**Comment by lsbardel** [comment]
The current pypi version ``1.0.5`` should work for both 3.4.3 and 3.5 and the error above should not occur in either versions. Can you check your version?
```python
import pulsar
pulsar.__version__
```
The test suite does not yet fully pass on python 3.5, that is why 3.5 is not yet fully supported. It will be soon enough.

**Comment by thedrow** [comment]
That's exactly what I have and it's not working properly.
