### ISSUE TITLE
TypeError in HttpRedirect.location property

### ISSUE THREAD

**Issue by msornay** [quantmind/pulsar#178]
Hello,

Versions : Python 3.4, Pulsar 1.0.5

```
from pulsar.utils.exceptions import HttpRedirect
>>> HttpRedirect(location='https://pythonhosted.org/pulsar').location
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "[...]pulsar/lib/python3.4/site-packages/pulsar/utils/exceptions.py", line 151, in location
    return self.headers['location']
TypeError: list indices must be integers, not str
```

Probably a trivial fix but i'm still having big issues with the test suite, sorry.

**Comment by lsbardel** [comment]
Thanks for reporting.
It is now fixed in master.
