### ISSUE TITLE
Handling common timeout exception

### ISSUE THREAD

**Issue by lsbardel** [quantmind/pulsar#185]
This exception is thrown whenever a timeout occurs.
We need to understand where the timeout is and handle it in a better way (We don't want to see the same meaningless stack trace every time)

```
Task exception was never retrieved
future: <Task finished coro=<_async() done, defined at /opt/bmll/bmlltech/venv/src/pulsar/pulsar/apps/wsgi/handlers.py:163> exception=RuntimeError('Cannot set content. Already iterated',)>
Traceback (most recent call last):
  File "/opt/bmll/bmlltech/venv/src/pulsar/pulsar/apps/wsgi/handlers.py", line 169, in _async
    response = yield from response
  File "/usr/lib/python3.4/asyncio/futures.py", line 386, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.4/asyncio/tasks.py", line 287, in _wakeup
    value = future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 267, in result
    raise CancelledError
concurrent.futures._base.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/asyncio/tasks.py", line 234, in _step
    result = coro.throw(exc)
  File "/opt/bmll/bmlltech/venv/src/pulsar/pulsar/apps/wsgi/handlers.py", line 176, in _async
    response = handle_wsgi_error(environ, exc)
  File "/opt/bmll/bmlltech/venv/src/pulsar/pulsar/apps/wsgi/utils.py", line 258, in handle_wsgi_error
    response.content = content
  File "/opt/bmll/bmlltech/venv/src/pulsar/pulsar/apps/wsgi/wrappers.py", line 193, in content
    raise RuntimeError('Cannot set content. Already iterated')
RuntimeError: Cannot set content. Already iterated
```

**Comment by lsbardel** [comment]
fixed

**Comment by bright-pan** [comment]
cool
