### ISSUE TITLE
test failure

### ISSUE THREAD

**Issue by bright-pan** [quantmind/pulsar#206]
i run test command for pulsar, but it failure:

```
python runtests.py
3.5.1 (default, Dec 30 2015, 01:45:36)
[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)]
ssssssssss.................................................................................................sssssss.....................................s.......................................................s..ssssssssssss............sssssssssssssssssssssssssssssssssssssssssssssssssssss.....s...........................................................................ssssssssssssss.................................................................................................sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss..xx.x......................................ssssssssssssssss..............................F....................................................ssssssss............................................................................................................
======================================================================
FAIL: utils.slugify.test_manager (tests.utils.slugify.TestSlugify)
----------------------------------------------------------------------
Traceback (most recent call last):

  File "/Users/jason/pulsar/pulsar/apps/test/runner.py", line 160, in _run_safe
    coro = method()

  File "/Users/jason/pulsar/tests/utils/slugify.py", line 22, in test_manager
    self.assertEqual(r, "cest-deja-lete")

  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/unittest/case.py", line 820, in assertEqual
    assertion_func(first, second, msg=msg)

  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/unittest/case.py", line 1193, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))

  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/unittest/case.py", line 665, in fail
    raise self.failureException(msg)

AssertionError: 'cest-de-ja-le-te' != 'cest-deja-lete'
- cest-de-ja-le-te
?        -     -
+ cest-deja-lete


Ran 617 tests in 75.367s

FAILED (failures=1, skipped=434, expected failures=3)

Bye (exit code = 2)
```

**Comment by lsbardel** [comment]
It fails because it requires the [unidecode](https://pypi.python.org/pypi/Unidecode) package for testing. It is a [soft dependency of pulsar](https://github.com/quantmind/pulsar#add-ons).
I've added the skip decorator. Thanks for reporting
