### ISSUE TITLE
Accessing external app in websocket handler with Pulsar 1.2 throws TypeError

### ISSUE THREAD

**Issue by davebshow** [quantmind/pulsar#220]
With Pulsar 1.1.3. we can access an external app using `yield from pulsar.get_application('app')` from a websocket handler. However, upon updating to pulsar 1.2, this same code throws ``TypeError: can't pickle generator objects``. Is this the expected behavior? If so, what is the correct design pattern to access an external app using a websocket handler?

Here is a simplified example of our websocket handler:

```python
import asyncio
import pulsar
from pulsar.apps import ws, wsgi


class Echo(ws.WS):

    def on_bytes(self, websocket, msg):
        websocket._loop.call_soon(
            pulsar.ensure_future, self._call(websocket, msg))

    @asyncio.coroutine
    def _call(self, websocket, msg):
        # This is actually an independent app, not wsgi
        app = yield from pulsar.get_application('wsgi')
        # Do some things with app
        websocket.write(msg)
        websocket.write_close()


class Site(wsgi.LazyWsgi):

    def setup(self, environ):
        return wsgi.WsgiHandler(
            [ws.WebSocket('/', Echo())])

def server(**kwargs):
    return wsgi.WSGIServer(callable=Site(), **kwargs)
```

The client uses aiohttp, like this:

```python 
import asyncio
import aiohttp

@asyncio.coroutine
def main():
    client = yield from aiohttp.ws_connect('http://127.0.0.1:8060/')
    client.send_bytes(b"hello")
    try:
        while True:
            resp = yield from client.receive()
            if resp.tp == aiohttp.MsgType.close:
                break
            print(resp.data)
    finally:
        yield from client.close()
```

This is the traceback using pulsar 1.2:

```
13:35:40 [p=8978, t=140174375688000, ERROR, asyncio] Task exception was never retrieved
future: <Task finished coro=<_on_message() done, defined at /home/davebshow/.virtualenvs/goblin_examples/lib/python3.5/site-packages/pulsar/async/mailbox.py:196> exception=TypeError("can't pickle generator objects",) created at /home/davebshow/.virtualenvs/goblin_examples/lib/python3.5/site-packages/pulsar/async/futures.py:172>
source_traceback: Object created at (most recent call last):
  File "ws.py", line 31, in <module>
    server().start()
  File "/home/davebshow/.virtualenvs/goblin_examples/lib/python3.5/site-packages/pulsar/apps/__init__.py", line 356, in start
    arbiter.start()
  File "/home/davebshow/.virtualenvs/goblin_examples/lib/python3.5/site-packages/pulsar/async/actor.py", line 285, in start
    self._run()
  File "/home/davebshow/.virtualenvs/goblin_examples/lib/python3.5/site-packages/pulsar/async/actor.py", line 434, in _run
    exc = self.__impl.run_actor(self)
  File "/home/davebshow/.virtualenvs/goblin_examples/lib/python3.5/site-packages/pulsar/async/concurrency.py", line 133, in run_actor
    actor._loop.run_forever()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 295, in run_forever
    self._run_once()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 1246, in _run_once
    handle._run()
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/usr/lib/python3.5/asyncio/selector_events.py", line 671, in _read_ready
    self._protocol.data_received(data)
  File "/home/davebshow/.virtualenvs/goblin_examples/lib/python3.5/site-packages/pulsar/async/mailbox.py", line 175, in data_received
    self._on_message(message)
  File "/home/davebshow/.virtualenvs/goblin_examples/lib/python3.5/site-packages/pulsar/async/futures.py", line 172, in _
    return ensure_future(coro, loop=loop)
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/davebshow/.virtualenvs/goblin_examples/lib/python3.5/site-packages/pulsar/async/mailbox.py", line 240, in _on_message
    self._start(Message.callback(result, ack))
  File "/home/davebshow/.virtualenvs/goblin_examples/lib/python3.5/site-packages/pulsar/async/mailbox.py", line 188, in _start
    self._write(req)
  File "/home/davebshow/.virtualenvs/goblin_examples/lib/python3.5/site-packages/pulsar/async/mailbox.py", line 243, in _write
    obj = pickle.dumps(req.data, protocol=2)
TypeError: can't pickle generator objects
```

**Comment by lsbardel** [comment]
That is a regression introduced in 1.2, thanks for the report.
I've fixed the issue in the commit above.
Please test from master and let me know if it works for you.

**Comment by davebshow** [comment]
Everything is be working as expected now. Thanks @lsbardel!
