### ISSUE TITLE
Installation regression

### ISSUE THREAD

**Issue by Manmadescience** [quantmind/pulsar#223]
I suppose this issue can be prioritized as low. I'm maintaining an ebuild file for Gentoo Linux to install pulsar as a system dependency. Since v1.3.0 (f110e30) I'm not able to build the package ending in a following error (here a sample error with latest stable):

> \>\>\> Compiling source in /var/tmp/portage/dev-python/pulsar-1.3.2/work/pulsar-1.3.2 ...
 * python3_5: running distutils-r1_run_phase distutils-r1_python_compile
/usr/bin/python3.5 setup.py build
Traceback (most recent call last):
  File "/usr/lib64/python3.5/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib64/python3.5/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib64/python3.5/site-packages/setuptools/command/bdist_egg.py", line 152, in run
    self.run_command("egg_info")
  File "/usr/lib64/python3.5/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib64/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib64/python3.5/site-packages/setuptools/command/egg_info.py", line 174, in run
    self.mkpath(self.egg_info)
  File "/usr/lib64/python3.5/distutils/cmd.py", line 339, in mkpath
    dir_util.mkpath(name, mode, dry_run=self.dry_run)
  File "/usr/lib64/python3.5/distutils/dir_util.py", line 70, in mkpath
    os.mkdir(head, mode)
  File "/usr/lib64/python3.5/site-packages/setuptools/sandbox.py", line 296, in wrap
    path = self._remap_input(name,path,*args,**kw)
  File "/usr/lib64/python3.5/site-packages/setuptools/sandbox.py", line 436, in _remap_input
    self._violation(operation, os.path.realpath(path), *args, **kw)
  File "/usr/lib64/python3.5/site-packages/setuptools/sandbox.py", line 392, in _violation
    raise SandboxViolation(operation, args, kw)
setuptools.sandbox.SandboxViolation: SandboxViolation: mkdir('/var/tmp/portage/dev-python/pulsar-1.3.2/work/pulsar-1.3.2-python3_5/wheel.egg-info', 511) {}
>
> The package setup script has attempted to modify files on your system
that are not within the EasyInstall build area, and has been aborted.
>
> This package cannot be safely installed by EasyInstall, and may not
support alternate installation locations even if you run its setup
script by hand.  Please inform the package's author and the EasyInstall
maintainers to find out if a fix or workaround is available.

The ebuild file itself does not change except for the version tag.

**Comment by lsbardel** [comment]
How can I replicate the issue?
What command are you running?
It looks like an issue with the wheel.egg-info.

**Comment by Manmadescience** [comment]
Unfortunately, I don't see a possibility to reproduce the issue without installing Gentoo (at least a minimal installation on a VM) and integrating the custom ebuild via layman. At least I did a bisect and found out that the issue was first introduced in 83ce3e3.

**Comment by Manmadescience** [comment]
After looking further into the diff of the mentioned commit, I found the issue source. I simply forgot to declare a dependency on the wheel package, thus the problem was entirely on my side. Sorry! Closing this issue as nothing to fix.
