### ISSUE TITLE
pickle error

### ISSUE THREAD

**Issue by robgil** [quantmind/pulsar#246]
When using pex to build relocatable virtualenv using pulsar, I'm getting pickle errors on the pulsar class. 

Python 3.5.2
Pulsar 1.3.4

```
$ ./my_virtualenv.pex manage.py 
Traceback (most recent call last):
  File ".bootstrap/_pex/pex.py", line 326, in execute
  File ".bootstrap/_pex/pex.py", line 258, in _wrap_coverage
  File ".bootstrap/_pex/pex.py", line 290, in _wrap_profiling
  File ".bootstrap/_pex/pex.py", line 372, in _execute
  File ".bootstrap/_pex/pex.py", line 382, in execute_interpreter
  File ".bootstrap/_pex/pex.py", line 412, in execute_content
  File ".bootstrap/_pex/compatibility.py", line 72, in exec_function
  File "manage.py", line 49, in <module>
    server().start()
  File "/Users/rgil/.pex/install/pulsar-1.3.4-cp35-cp35m-macosx_10_11_x86_64.whl.06c2cdd8116d899d416db4a5a451ec3078d2c992/pulsar-1.3.4-cp35-cp35m-macosx_10_11_x86_64.whl/pulsar/apps/__init__.py", line 352, in start
    on_start = self()
  File "/Users/rgil/.pex/install/pulsar-1.3.4-cp35-cp35m-macosx_10_11_x86_64.whl.06c2cdd8116d899d416db4a5a451ec3078d2c992/pulsar-1.3.4-cp35-cp35m-macosx_10_11_x86_64.whl/pulsar/apps/__init__.py", line 461, in __call__
    actor = pulsar.arbiter(cfg=self.cfg.clone())
  File "/Users/rgil/.pex/install/pulsar-1.3.4-cp35-cp35m-macosx_10_11_x86_64.whl.06c2cdd8116d899d416db4a5a451ec3078d2c992/pulsar-1.3.4-cp35-cp35m-macosx_10_11_x86_64.whl/pulsar/utils/config.py", line 387, in clone
    return pickle.loads(pickle.dumps(self))
_pickle.PicklingError: Can't pickle <class '__main__.Site'>: attribute lookup Site on __main__ failed
```

manage.py
```
from flask import Flask, make_response
from pulsar.apps import wsgi
import api as api_v1
import common as common
import logging
from logging.config import fileConfig
import yaml
import os

#print(logging.Logger.manager.loggerDict)

with open(os.path.dirname(os.path.realpath(__file__)) + '/logging.yml') as f:
    conf = yaml.load(f)
    conf.setdefault('version', 1)
    logging.config.dictConfig(conf)

logger = logging.getLogger(__name__)


def Events():
    """Events flask app."""
    app = Flask(__name__)
    app.register_blueprint(common.common)
    app.register_blueprint(api_v1.api, url_prefix='/v1')

    # Works
    #app.register_blueprint(api.api)

    @app.errorhandler(404)
    def not_found(e):
        return make_response("404 Page", 404)

    return app


class Site(wsgi.LazyWsgi):

    def setup(self, environ=None):
        app = Events()
        return wsgi.WsgiHandler((wsgi.wait_for_body_middleware,
                                 wsgi.middleware_in_executor(app)))


def server(**kwargs):
    return wsgi.WSGIServer(Site(), **kwargs)


if __name__ == '__main__':  # pragma    nocover
    server().start()

```

Creating the pex
```
pip install pex
pip install wheel
pex --disable-cache -v -r <(pip freeze) api/v1/ api/common/ monometrics -o my_virtualenv.pex 
```

**Comment by lsbardel** [comment]
I've never used ``pex`` before.
The Site object is picklable if the Site class is visible in the ``__main__``.
It looks like ``pex`` has removed that class from the ``__main__``.
If you need help, can you provide an [mcve](http://stackoverflow.com/help/mcve)? The example above requires modules not available.

**Comment by robgil** [comment]
Yup. I'll work this up.

**Comment by robgil** [comment]
Here it is. Pex is pretty neat, but I would be open to other suggestions for deploying python apps. I'm trying to avoid either baking images or dealing with docker nonsense.

https://github.com/robgil/pulsar-pex

**Comment by robgil** [comment]
I moved away from Pex to using newer versions of pip. New versions of pip allow you to store your compiled wheel files. It makes for an easier deploy.

The following is the relevant bits in the .travis.yml
```
install:
   - pip install virtualenv
   - virtualenv --always-copy ../mono-events
   - mkdir .cache/
   - . bin/activate && pip download -d .cache/ -r requirements.txt && pip install --find-links .cache/ -r requirements.txt

before_deploy:
  - rm -rf bin/ include/ lib/
  - zip -r latest * .cache
  - mkdir -p upload_dir/$TRAVIS_REPO_SLUG/$TRAVIS_BRANCH/
  - mv latest.zip upload_dir/$TRAVIS_REPO_SLUG/$TRAVIS_BRANCH/$TRAVIS_BUILD_NUMBER.zip
```

Once deployed to the server, the following will set up the virtualenv without needing internet, and without building.

```
cd /<virtualenv path>
virtualenv -p /<path to python>/bin/python3.5 /<virtualenv path>/
. bin/activate
pip install --find-links .cache/ -r requirements.txt
```

Thanks again for looking at this and lending an ear while I learn :)
