### ISSUE TITLE
Not working with Python 3.7 on Windows

### ISSUE THREAD

**Issue by TTimo** [quantmind/pulsar#315]
* **pulsar version**: 0c945134 (current git master HEAD)
* **python version**:

Python 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 17:00:18) [MSC v.1900 64 bit (AMD64)]
and
Python 3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 14:57:15) [MSC v.1915 64 bit (AMD64)]

* **platform**:

Windows 10

## Description

With Python 3.6 some tests fail (several http.proxy.*), but overall Pulsar seems operable.
With Python 3.7 tests fail to even start:

```
ttimo_000@VANGUARD /c/d/R/pulsar> /cygdrive/c/Python37/python.exe ./setup.py test
running test
running egg_info
writing pulsar.egg-info\PKG-INFO
writing dependency_links to pulsar.egg-info\dependency_links.txt
writing entry points to pulsar.egg-info\entry_points.txt
writing requirements to pulsar.egg-info\requires.txt
writing top-level names to pulsar.egg-info\top_level.txt
reading manifest file 'pulsar.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files matching '*.pyd' found anywhere in distribution
warning: no previously-included files matching '*.so' found anywhere in distribution
warning: no previously-included files matching '*.mp4' found anywhere in distribution
writing manifest file 'pulsar.egg-info\SOURCES.txt'
running build_ext
WARNING: C extensions could not be compiled: Cython not installed
running test
running egg_info
writing pulsar.egg-info\PKG-INFO
writing dependency_links to pulsar.egg-info\dependency_links.txt
writing entry points to pulsar.egg-info\entry_points.txt
writing requirements to pulsar.egg-info\requires.txt
writing top-level names to pulsar.egg-info\top_level.txt
reading manifest file 'pulsar.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files matching '*.pyd' found anywhere in distribution
warning: no previously-included files matching '*.so' found anywhere in distribution
warning: no previously-included files matching '*.mp4' found anywhere in distribution
writing manifest file 'pulsar.egg-info\SOURCES.txt'
running build_ext
Traceback (most recent call last):
  File "./setup.py", line 104, in <module>
    run_setup(False)
  File "./setup.py", line 93, in run_setup
    setup(**params)
  File "C:\Python37\lib\site-packages\setuptools\__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "C:\Python37\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Python37\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "C:\Python37\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Python37\lib\site-packages\setuptools\command\test.py", line 226, in run
    self.run_tests()
  File "D:\Roomored\pulsar\pulsar\cmds\test.py", line 74, in run_tests
    from pulsar.apps.test import TestSuite
  File "D:\Roomored\pulsar\pulsar\apps\__init__.py", line 68
    from ..async.monitor import arbiter
               ^
SyntaxError: invalid syntax
```

## Expected behaviour

At least the same level of functionality as with Python 3.6

## Actual behaviour

I could pip install from PyPI in my Python 3.7 installation, but tests are failing, and the simplest examples fail with the same errors.

## Steps to reproduce

Straightforward, see above.

**Comment by TTimo** [comment]
Oh I didn't see pull request #313 I will have to try
